/*
 *  Copyright 2022 UnitTestBot contributors (utbot.org)
 * <p>
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * <p>
 *  http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package org.utbot.jacodb.impl.storage.jooq


import org.jooq.Schema
import org.jooq.impl.CatalogImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        val DEFAULT_CATALOG = org.utbot.jacodb.impl.storage.jooq.DefaultCatalog()
    }

    /**
     * The schema <code>DEFAULT_SCHEMA</code>.
     */
    val DEFAULT_SCHEMA get() = org.utbot.jacodb.impl.storage.jooq.DefaultSchema.Companion.DEFAULT_SCHEMA

    override fun getSchemas(): List<Schema> = listOf(
        org.utbot.jacodb.impl.storage.jooq.DefaultSchema.Companion.DEFAULT_SCHEMA
    )
}
