/*
 *  Copyright 2022 UnitTestBot contributors (utbot.org)
 * <p>
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * <p>
 *  http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.usvm.jacodb.gen

import java.io.BufferedReader

val ptrMap: MutableMap<Int, Any> = mutableMapOf()
val structToPtrMap: MutableMap<Any, Int> = mutableMapOf()
val ptrToJacoMap: MutableMap<Int, Any> = mutableMapOf()
val mapDec: Map<String, (BufferedReader, Int)->Any?> = mapOf(
    "Int" to ::readInteger,
    "Short" to ::readInteger,
    "Long" to ::readInteger,
	"ULong" to ::readULong,
    "Float" to ::readReal,
    "Double" to ::readReal,
    "String" to ::readString,
    "Boolean" to ::readBoolean,
    "nil" to ::readNil,

    "array" to ::readArray,
    "map" to ::readMap,
	"types_instanceLookup" to ::read_types_instanceLookup,
	"ast_ArrayType" to ::read_ast_ArrayType,
	"ast_CommClause" to ::read_ast_CommClause,
	"ssa_ChangeType" to ::read_ssa_ChangeType,
	"types_TypeList" to ::read_types_TypeList,
	"big_Int" to ::read_big_Int,
	"ast_ParenExpr" to ::read_ast_ParenExpr,
	"ast_StructType" to ::read_ast_StructType,
	"ast_ReturnStmt" to ::read_ast_ReturnStmt,
	"ssa_CallCommon" to ::read_ssa_CallCommon,
	"types_Scope" to ::read_types_Scope,
	"types_Var" to ::read_types_Var,
	"ssa_Alloc" to ::read_ssa_Alloc,
	"ssa_lblock" to ::read_ssa_lblock,
	"big_Rat" to ::read_big_Rat,
	"ast_BinaryExpr" to ::read_ast_BinaryExpr,
	"ssa_MultiConvert" to ::read_ssa_MultiConvert,
	"types_Func" to ::read_types_Func,
	"types_importKey" to ::read_types_importKey,
	"typeutil_entry" to ::read_typeutil_entry,
	"types_Interface" to ::read_types_Interface,
	"ast_ValueSpec" to ::read_ast_ValueSpec,
	"ast_LabeledStmt" to ::read_ast_LabeledStmt,
	"ast_TypeSpec" to ::read_ast_TypeSpec,
	"types_exprInfo" to ::read_types_exprInfo,
	"types_actionDesc" to ::read_types_actionDesc,
	"typeutil_Map" to ::read_typeutil_Map,
	"ast_SliceExpr" to ::read_ast_SliceExpr,
	"ssa_Slice" to ::read_ssa_Slice,
	"ast_TypeAssertExpr" to ::read_ast_TypeAssertExpr,
	"ast_GoStmt" to ::read_ast_GoStmt,
	"ast_File" to ::read_ast_File,
	"types_Label" to ::read_types_Label,
	"generatedInlineStruct_000" to ::read_generatedInlineStruct_000,
	"ssa_tpWalker" to ::read_ssa_tpWalker,
	"constant_ratVal" to ::read_constant_ratVal,
	"ast_IfStmt" to ::read_ast_IfStmt,
	"ssa_If" to ::read_ssa_If,
	"types_TypeAndValue" to ::read_types_TypeAndValue,
	"ssa_FieldAddr" to ::read_ssa_FieldAddr,
	"ssa_Convert" to ::read_ssa_Convert,
	"ssa_Index" to ::read_ssa_Index,
	"token_File" to ::read_token_File,
	"types_TypeParamList" to ::read_types_TypeParamList,
	"ast_SelectorExpr" to ::read_ast_SelectorExpr,
	"types_declInfo" to ::read_types_declInfo,
	"types_term" to ::read_types_term,
	"ast_SendStmt" to ::read_ast_SendStmt,
	"ssa_Lookup" to ::read_ssa_Lookup,
	"ast_BasicLit" to ::read_ast_BasicLit,
	"types_monoEdge" to ::read_types_monoEdge,
	"ssa_Defer" to ::read_ssa_Defer,
	"ssa_MakeChan" to ::read_ssa_MakeChan,
	"types_Instance" to ::read_types_Instance,
	"types_Initializer" to ::read_types_Initializer,
	"types_Struct" to ::read_types_Struct,
	"ast_RangeStmt" to ::read_ast_RangeStmt,
	"ssa_IndexAddr" to ::read_ssa_IndexAddr,
	"ssa_Type" to ::read_ssa_Type,
	"ssa_Package" to ::read_ssa_Package,
	"ast_CommentGroup" to ::read_ast_CommentGroup,
	"ast_CompositeLit" to ::read_ast_CompositeLit,
	"ssa_Return" to ::read_ssa_Return,
	"ssa_Program" to ::read_ssa_Program,
	"sync_RWMutex" to ::read_sync_RWMutex,
	"atomic_Int32" to ::read_atomic_Int32,
	"types_Selection" to ::read_types_Selection,
	"types_monoVertex" to ::read_types_monoVertex,
	"ast_SelectStmt" to ::read_ast_SelectStmt,
	"types_Basic" to ::read_types_Basic,
	"ast_KeyValueExpr" to ::read_ast_KeyValueExpr,
	"ssa_Builtin" to ::read_ssa_Builtin,
	"ssa_Panic" to ::read_ssa_Panic,
	"ssa_TypeAssert" to ::read_ssa_TypeAssert,
	"ssa_MapUpdate" to ::read_ssa_MapUpdate,
	"types_object" to ::read_types_object,
	"ast_FuncType" to ::read_ast_FuncType,
	"ast_BlockStmt" to ::read_ast_BlockStmt,
	"ssa_domInfo" to ::read_ssa_domInfo,
	"ssa_targets" to ::read_ssa_targets,
	"ssa_Extract" to ::read_ssa_Extract,
	"ssa_Range" to ::read_ssa_Range,
	"ast_TypeSwitchStmt" to ::read_ast_TypeSwitchStmt,
	"token_FileSet" to ::read_token_FileSet,
	"ast_Scope" to ::read_ast_Scope,
	"ssa_BasicBlock" to ::read_ssa_BasicBlock,
	"types_Slice" to ::read_types_Slice,
	"ssa_NamedConst" to ::read_ssa_NamedConst,
	"ssa_Call" to ::read_ssa_Call,
	"types_monoGraph" to ::read_types_monoGraph,
	"ssa_typeListMap" to ::read_ssa_typeListMap,
	"types_Checker" to ::read_types_Checker,
	"types_Union" to ::read_types_Union,
	"typeutil_MethodSetCache" to ::read_typeutil_MethodSetCache,
	"ast_ForStmt" to ::read_ast_ForStmt,
	"types_Info" to ::read_types_Info,
	"ast_Object" to ::read_ast_Object,
	"types__TypeSet" to ::read_types__TypeSet,
	"ssa_Store" to ::read_ssa_Store,
	"types_Signature" to ::read_types_Signature,
	"ast_Field" to ::read_ast_Field,
	"ast_CallExpr" to ::read_ast_CallExpr,
	"ssa_canonizer" to ::read_ssa_canonizer,
	"types_Pointer" to ::read_types_Pointer,
	"constant_stringVal" to ::read_constant_stringVal,
	"sync_Mutex" to ::read_sync_Mutex,
	"types_dotImportKey" to ::read_types_dotImportKey,
	"types_Nil" to ::read_types_Nil,
	"types_Chan" to ::read_types_Chan,
	"ast_UnaryExpr" to ::read_ast_UnaryExpr,
	"ssa_Phi" to ::read_ssa_Phi,
	"ast_MapType" to ::read_ast_MapType,
	"ast_InterfaceType" to ::read_ast_InterfaceType,
	"ssa_Function" to ::read_ssa_Function,
	"types_PkgName" to ::read_types_PkgName,
	"ssa_FreeVar" to ::read_ssa_FreeVar,
	"ssa_subster" to ::read_ssa_subster,
	"typeutil_Hasher" to ::read_typeutil_Hasher,
	"ast_DeclStmt" to ::read_ast_DeclStmt,
	"ssa_BinOp" to ::read_ssa_BinOp,
	"ssa_Field" to ::read_ssa_Field,
	"ssa_selection" to ::read_ssa_selection,
	"types_Config" to ::read_types_Config,
	"types_action" to ::read_types_action,
	"ssa_generic" to ::read_ssa_generic,
	"constant_intVal" to ::read_constant_intVal,
	"types_Map" to ::read_types_Map,
	"ast_ImportSpec" to ::read_ast_ImportSpec,
	"types_TypeName" to ::read_types_TypeName,
	"ssa_register" to ::read_ssa_register,
	"ssa_Const" to ::read_ssa_Const,
	"ast_ExprStmt" to ::read_ast_ExprStmt,
	"ssa_opaqueType" to ::read_ssa_opaqueType,
	"ssa_Parameter" to ::read_ssa_Parameter,
	"sync_Once" to ::read_sync_Once,
	"atomic_Uint32" to ::read_atomic_Uint32,
	"types_Builtin" to ::read_types_Builtin,
	"ast_StarExpr" to ::read_ast_StarExpr,
	"types_Context" to ::read_types_Context,
	"types_MethodSet" to ::read_types_MethodSet,
	"types_Const" to ::read_types_Const,
	"ast_FuncLit" to ::read_ast_FuncLit,
	"ssa_Go" to ::read_ssa_Go,
	"constant_complexVal" to ::read_constant_complexVal,
	"types_TypeParam" to ::read_types_TypeParam,
	"types_ctxtEntry" to ::read_types_ctxtEntry,
	"ast_FuncDecl" to ::read_ast_FuncDecl,
	"types_environment" to ::read_types_environment,
	"ssa_anInstruction" to ::read_ssa_anInstruction,
	"ast_Ellipsis" to ::read_ast_Ellipsis,
	"types_Package" to ::read_types_Package,
	"ast_FieldList" to ::read_ast_FieldList,
	"ast_AssignStmt" to ::read_ast_AssignStmt,
	"ast_IndexExpr" to ::read_ast_IndexExpr,
	"ast_IncDecStmt" to ::read_ast_IncDecStmt,
	"ssa_ChangeInterface" to ::read_ssa_ChangeInterface,
	"token_lineInfo" to ::read_token_lineInfo,
	"ssa_Select" to ::read_ssa_Select,
	"ssa_SelectState" to ::read_ssa_SelectState,
	"ssa_Send" to ::read_ssa_Send,
	"ssa_SliceToArrayPointer" to ::read_ssa_SliceToArrayPointer,
	"ast_Ident" to ::read_ast_Ident,
	"ast_Comment" to ::read_ast_Comment,
	"types_instance" to ::read_types_instance,
	"ssa_MakeInterface" to ::read_ssa_MakeInterface,
	"ssa_MakeMap" to ::read_ssa_MakeMap,
	"types_Named" to ::read_types_Named,
	"types_Term" to ::read_types_Term,
	"types_Array" to ::read_types_Array,
	"ssa_UnOp" to ::read_ssa_UnOp,
	"ssa_MakeClosure" to ::read_ssa_MakeClosure,
	"ssa_MakeSlice" to ::read_ssa_MakeSlice,
	"ssa_RunDefers" to ::read_ssa_RunDefers,
	"ast_CaseClause" to ::read_ast_CaseClause,
	"ast_BranchStmt" to ::read_ast_BranchStmt,
	"ast_DeferStmt" to ::read_ast_DeferStmt,
	"ast_ChanType" to ::read_ast_ChanType,
	"ssa_Jump" to ::read_ssa_Jump,
	"ssa_Next" to ::read_ssa_Next,
	"types_Tuple" to ::read_types_Tuple,
	"ast_GenDecl" to ::read_ast_GenDecl,
	"ast_SwitchStmt" to ::read_ast_SwitchStmt,
	"ssa_Global" to ::read_ssa_Global
)

fun StartDeserializer(buffReader: BufferedReader): Any? {
    val line = buffReader.readLine()
    val split = line.split(" ")
    val readType = split[0]
    var id = -1
    if (split.size > 1) {
        id = split[1].toInt()
    }
    return mapDec[readType]?.invoke(buffReader, id)
}
