package org.utbot.jcdb.api.ext

import kotlinx.metadata.KmConstructor
import kotlinx.metadata.KmFunction
import kotlinx.metadata.jvm.KotlinClassHeader
import kotlinx.metadata.jvm.KotlinClassMetadata
import kotlinx.metadata.jvm.signature
import org.utbot.jcdb.api.JcClassOrInterface
import org.utbot.jcdb.api.JcMethod

/**
 * Returns [KotlinClassMetadata] instance for the class if it was generated by Kotlin.
 * See docs for [Metadata] for more info on how it is represented in bytecode and what it contains.
 */
@Suppress("UNCHECKED_CAST")
val JcClassOrInterface.kMetadata: KotlinClassMetadata?
    get() {
        val kmParameters = annotations.firstOrNull { it.matches("kotlin.Metadata") }?.values ?: return null
        val kmHeader = KotlinClassHeader(
            kmParameters["k"] as? Int,
            (kmParameters["mv"] as? List<Int>)?.toIntArray(),
            (kmParameters["d1"] as? List<String>)?.toTypedArray(),
            (kmParameters["d2"] as? List<String>)?.toTypedArray(),
            kmParameters["xs"] as? String,
            kmParameters["pn"] as? String,
            kmParameters["xi"] as? Int,
        )
        return KotlinClassMetadata.read(kmHeader)
    }

val JcMethod.kmFunction: KmFunction?
    get() =
        enclosingClass.kMetadata?.functions?.firstOrNull { it.signature?.name == name && it.signature?.desc == description }

val JcMethod.kmConstructor: KmConstructor?
    get() =
        enclosingClass.kMetadata?.constructors?.firstOrNull { it.signature?.name == name && it.signature?.desc == description }

private val KotlinClassMetadata.functions: List<KmFunction>
    get() =
        when(this) {
            is KotlinClassMetadata.Class -> toKmClass().functions
            is KotlinClassMetadata.FileFacade -> toKmPackage().functions
            is KotlinClassMetadata.MultiFileClassPart -> toKmPackage().functions
            else -> listOf()
        }

private val KotlinClassMetadata.constructors: List<KmConstructor>
    get() = (this as? KotlinClassMetadata.Class)?.toKmClass()?.constructors ?: emptyList()