DROP TABLE IF EXISTS "BytecodeLocations";
DROP TABLE IF EXISTS "Symbols";
DROP TABLE IF EXISTS "OuterClasses";
DROP TABLE IF EXISTS "Methods";
DROP TABLE IF EXISTS "Classes";
DROP TABLE IF EXISTS "ClassHierarchies";
DROP TABLE IF EXISTS "ClassInnerClasses";
DROP TABLE IF EXISTS "MethodParameters";
DROP TABLE IF EXISTS "Fields";
DROP TABLE IF EXISTS "Annotations";
DROP TABLE IF EXISTS "AnnotationValues";
DROP INDEX IF EXISTS "Symbols_name";
DROP INDEX IF EXISTS "Classes_name";
DROP INDEX IF EXISTS "Methods_class_id_name_desc";
DROP INDEX IF EXISTS "Fields_class_id_name";
DROP INDEX IF EXISTS "Class Hierarchies";
