/*
 *  Copyright 2022 UnitTestBot contributors (utbot.org)
 * <p>
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 * <p>
 *  http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl
import org.utbot.jcdb.impl.storage.jooq.tables.Fields


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FieldsRecord() : UpdatableRecordImpl<FieldsRecord>(Fields.FIELDS), Record6<Long?, Int?, Long?, String?, Long?, Long?> {

    var id: Long?
        set(value) = set(0, value)
        get() = get(0) as Long?

    var access: Int?
        set(value) = set(1, value)
        get() = get(1) as Int?

    var name: Long?
        set(value) = set(2, value)
        get() = get(2) as Long?

    var signature: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    var fieldClass: Long?
        set(value) = set(4, value)
        get() = get(4) as Long?

    var classId: Long?
        set(value) = set(5, value)
        get() = get(5) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<Long?, Int?, Long?, String?, Long?, Long?> = super.fieldsRow() as Row6<Long?, Int?, Long?, String?, Long?, Long?>
    override fun valuesRow(): Row6<Long?, Int?, Long?, String?, Long?, Long?> = super.valuesRow() as Row6<Long?, Int?, Long?, String?, Long?, Long?>
    override fun field1(): Field<Long?> = Fields.FIELDS.ID
    override fun field2(): Field<Int?> = Fields.FIELDS.ACCESS
    override fun field3(): Field<Long?> = Fields.FIELDS.NAME
    override fun field4(): Field<String?> = Fields.FIELDS.SIGNATURE
    override fun field5(): Field<Long?> = Fields.FIELDS.FIELD_CLASS
    override fun field6(): Field<Long?> = Fields.FIELDS.CLASS_ID
    override fun component1(): Long? = id
    override fun component2(): Int? = access
    override fun component3(): Long? = name
    override fun component4(): String? = signature
    override fun component5(): Long? = fieldClass
    override fun component6(): Long? = classId
    override fun value1(): Long? = id
    override fun value2(): Int? = access
    override fun value3(): Long? = name
    override fun value4(): String? = signature
    override fun value5(): Long? = fieldClass
    override fun value6(): Long? = classId

    override fun value1(value: Long?): FieldsRecord {
        this.id = value
        return this
    }

    override fun value2(value: Int?): FieldsRecord {
        this.access = value
        return this
    }

    override fun value3(value: Long?): FieldsRecord {
        this.name = value
        return this
    }

    override fun value4(value: String?): FieldsRecord {
        this.signature = value
        return this
    }

    override fun value5(value: Long?): FieldsRecord {
        this.fieldClass = value
        return this
    }

    override fun value6(value: Long?): FieldsRecord {
        this.classId = value
        return this
    }

    override fun values(value1: Long?, value2: Int?, value3: Long?, value4: String?, value5: Long?, value6: Long?): FieldsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised FieldsRecord
     */
    constructor(id: Long? = null, access: Int? = null, name: Long? = null, signature: String? = null, fieldClass: Long? = null, classId: Long? = null): this() {
        this.id = id
        this.access = access
        this.name = name
        this.signature = signature
        this.fieldClass = fieldClass
        this.classId = classId
    }
}
