/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables.references


import org.utbot.jcdb.impl.storage.jooq.tables.Annotations
import org.utbot.jcdb.impl.storage.jooq.tables.Annotationvalues
import org.utbot.jcdb.impl.storage.jooq.tables.Bytecodelocations
import org.utbot.jcdb.impl.storage.jooq.tables.Calls
import org.utbot.jcdb.impl.storage.jooq.tables.Classes
import org.utbot.jcdb.impl.storage.jooq.tables.Classhierarchies
import org.utbot.jcdb.impl.storage.jooq.tables.Classinnerclasses
import org.utbot.jcdb.impl.storage.jooq.tables.Fields
import org.utbot.jcdb.impl.storage.jooq.tables.Methodparameters
import org.utbot.jcdb.impl.storage.jooq.tables.Methods
import org.utbot.jcdb.impl.storage.jooq.tables.Outerclasses
import org.utbot.jcdb.impl.storage.jooq.tables.Symbols



/**
 * The table <code>Annotations</code>.
 */
val ANNOTATIONS: Annotations = Annotations.ANNOTATIONS

/**
 * The table <code>AnnotationValues</code>.
 */
val ANNOTATIONVALUES: Annotationvalues = Annotationvalues.ANNOTATIONVALUES

/**
 * The table <code>BytecodeLocations</code>.
 */
val BYTECODELOCATIONS: Bytecodelocations = Bytecodelocations.BYTECODELOCATIONS

/**
 * The table <code>Calls</code>.
 */
val CALLS: Calls = Calls.CALLS

/**
 * The table <code>Classes</code>.
 */
val CLASSES: Classes = Classes.CLASSES

/**
 * The table <code>ClassHierarchies</code>.
 */
val CLASSHIERARCHIES: Classhierarchies = Classhierarchies.CLASSHIERARCHIES

/**
 * The table <code>ClassInnerClasses</code>.
 */
val CLASSINNERCLASSES: Classinnerclasses = Classinnerclasses.CLASSINNERCLASSES

/**
 * The table <code>Fields</code>.
 */
val FIELDS: Fields = Fields.FIELDS

/**
 * The table <code>MethodParameters</code>.
 */
val METHODPARAMETERS: Methodparameters = Methodparameters.METHODPARAMETERS

/**
 * The table <code>Methods</code>.
 */
val METHODS: Methods = Methods.METHODS

/**
 * The table <code>OuterClasses</code>.
 */
val OUTERCLASSES: Outerclasses = Outerclasses.OUTERCLASSES

/**
 * The table <code>Symbols</code>.
 */
val SYMBOLS: Symbols = Symbols.SYMBOLS
