/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl
import org.utbot.jcdb.impl.storage.jooq.tables.Bytecodelocations


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BytecodelocationsRecord() : UpdatableRecordImpl<BytecodelocationsRecord>(Bytecodelocations.BYTECODELOCATIONS), Record6<Long?, String?, String?, Boolean?, Int?, Long?> {

    var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    var path: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    var hash: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    var runtime: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    var state: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    var updatedId: Long?
        set(value): Unit = set(5, value)
        get(): Long? = get(5) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<Long?, String?, String?, Boolean?, Int?, Long?> = super.fieldsRow() as Row6<Long?, String?, String?, Boolean?, Int?, Long?>
    override fun valuesRow(): Row6<Long?, String?, String?, Boolean?, Int?, Long?> = super.valuesRow() as Row6<Long?, String?, String?, Boolean?, Int?, Long?>
    override fun field1(): Field<Long?> = Bytecodelocations.BYTECODELOCATIONS.ID
    override fun field2(): Field<String?> = Bytecodelocations.BYTECODELOCATIONS.PATH
    override fun field3(): Field<String?> = Bytecodelocations.BYTECODELOCATIONS.HASH
    override fun field4(): Field<Boolean?> = Bytecodelocations.BYTECODELOCATIONS.RUNTIME
    override fun field5(): Field<Int?> = Bytecodelocations.BYTECODELOCATIONS.STATE
    override fun field6(): Field<Long?> = Bytecodelocations.BYTECODELOCATIONS.UPDATED_ID
    override fun component1(): Long? = id
    override fun component2(): String? = path
    override fun component3(): String? = hash
    override fun component4(): Boolean? = runtime
    override fun component5(): Int? = state
    override fun component6(): Long? = updatedId
    override fun value1(): Long? = id
    override fun value2(): String? = path
    override fun value3(): String? = hash
    override fun value4(): Boolean? = runtime
    override fun value5(): Int? = state
    override fun value6(): Long? = updatedId

    override fun value1(value: Long?): BytecodelocationsRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): BytecodelocationsRecord {
        this.path = value
        return this
    }

    override fun value3(value: String?): BytecodelocationsRecord {
        this.hash = value
        return this
    }

    override fun value4(value: Boolean?): BytecodelocationsRecord {
        this.runtime = value
        return this
    }

    override fun value5(value: Int?): BytecodelocationsRecord {
        this.state = value
        return this
    }

    override fun value6(value: Long?): BytecodelocationsRecord {
        this.updatedId = value
        return this
    }

    override fun values(value1: Long?, value2: String?, value3: String?, value4: Boolean?, value5: Int?, value6: Long?): BytecodelocationsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised BytecodelocationsRecord
     */
    constructor(id: Long? = null, path: String? = null, hash: String? = null, runtime: Boolean? = null, state: Int? = null, updatedId: Long? = null): this() {
        this.id = id
        this.path = path
        this.hash = hash
        this.runtime = runtime
        this.state = state
        this.updatedId = updatedId
    }
}
