/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables.records


import org.jooq.Field
import org.jooq.Record5
import org.jooq.Row5
import org.jooq.impl.TableRecordImpl
import org.utbot.jcdb.impl.storage.jooq.tables.Calls


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CallsRecord() : TableRecordImpl<CallsRecord>(Calls.CALLS), Record5<Long?, Long?, Long?, Long?, Long?> {

    var calleeClassHash: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    var calleeFieldHash: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    var calleeMethodHash: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    var callerClassHash: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    var locationId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row5<Long?, Long?, Long?, Long?, Long?> = super.fieldsRow() as Row5<Long?, Long?, Long?, Long?, Long?>
    override fun valuesRow(): Row5<Long?, Long?, Long?, Long?, Long?> = super.valuesRow() as Row5<Long?, Long?, Long?, Long?, Long?>
    override fun field1(): Field<Long?> = Calls.CALLS.CALLEE_CLASS_HASH
    override fun field2(): Field<Long?> = Calls.CALLS.CALLEE_FIELD_HASH
    override fun field3(): Field<Long?> = Calls.CALLS.CALLEE_METHOD_HASH
    override fun field4(): Field<Long?> = Calls.CALLS.CALLER_CLASS_HASH
    override fun field5(): Field<Long?> = Calls.CALLS.LOCATION_ID
    override fun component1(): Long? = calleeClassHash
    override fun component2(): Long? = calleeFieldHash
    override fun component3(): Long? = calleeMethodHash
    override fun component4(): Long? = callerClassHash
    override fun component5(): Long? = locationId
    override fun value1(): Long? = calleeClassHash
    override fun value2(): Long? = calleeFieldHash
    override fun value3(): Long? = calleeMethodHash
    override fun value4(): Long? = callerClassHash
    override fun value5(): Long? = locationId

    override fun value1(value: Long?): CallsRecord {
        this.calleeClassHash = value
        return this
    }

    override fun value2(value: Long?): CallsRecord {
        this.calleeFieldHash = value
        return this
    }

    override fun value3(value: Long?): CallsRecord {
        this.calleeMethodHash = value
        return this
    }

    override fun value4(value: Long?): CallsRecord {
        this.callerClassHash = value
        return this
    }

    override fun value5(value: Long?): CallsRecord {
        this.locationId = value
        return this
    }

    override fun values(value1: Long?, value2: Long?, value3: Long?, value4: Long?, value5: Long?): CallsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        return this
    }

    /**
     * Create a detached, initialised CallsRecord
     */
    constructor(calleeClassHash: Long? = null, calleeFieldHash: Long? = null, calleeMethodHash: Long? = null, callerClassHash: Long? = null, locationId: Long? = null): this() {
        this.calleeClassHash = calleeClassHash
        this.calleeFieldHash = calleeFieldHash
        this.calleeMethodHash = calleeMethodHash
        this.callerClassHash = callerClassHash
        this.locationId = locationId
    }
}
