/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl
import org.utbot.jcdb.impl.storage.jooq.tables.Classhierarchies


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ClasshierarchiesRecord() : UpdatableRecordImpl<ClasshierarchiesRecord>(Classhierarchies.CLASSHIERARCHIES), Record4<Long?, Long?, Long?, Boolean?> {

    var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    var classId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    var superId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    @set:JvmName("setIsClassRef")
    var isClassRef: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Long?, Long?, Long?, Boolean?> = super.fieldsRow() as Row4<Long?, Long?, Long?, Boolean?>
    override fun valuesRow(): Row4<Long?, Long?, Long?, Boolean?> = super.valuesRow() as Row4<Long?, Long?, Long?, Boolean?>
    override fun field1(): Field<Long?> = Classhierarchies.CLASSHIERARCHIES.ID
    override fun field2(): Field<Long?> = Classhierarchies.CLASSHIERARCHIES.CLASS_ID
    override fun field3(): Field<Long?> = Classhierarchies.CLASSHIERARCHIES.SUPER_ID
    override fun field4(): Field<Boolean?> = Classhierarchies.CLASSHIERARCHIES.IS_CLASS_REF
    override fun component1(): Long? = id
    override fun component2(): Long? = classId
    override fun component3(): Long? = superId
    override fun component4(): Boolean? = isClassRef
    override fun value1(): Long? = id
    override fun value2(): Long? = classId
    override fun value3(): Long? = superId
    override fun value4(): Boolean? = isClassRef

    override fun value1(value: Long?): ClasshierarchiesRecord {
        this.id = value
        return this
    }

    override fun value2(value: Long?): ClasshierarchiesRecord {
        this.classId = value
        return this
    }

    override fun value3(value: Long?): ClasshierarchiesRecord {
        this.superId = value
        return this
    }

    override fun value4(value: Boolean?): ClasshierarchiesRecord {
        this.isClassRef = value
        return this
    }

    override fun values(value1: Long?, value2: Long?, value3: Long?, value4: Boolean?): ClasshierarchiesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised ClasshierarchiesRecord
     */
    constructor(id: Long? = null, classId: Long? = null, superId: Long? = null, isClassRef: Boolean? = null): this() {
        this.id = id
        this.classId = classId
        this.superId = superId
        this.isClassRef = isClassRef
    }
}
