/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl
import org.utbot.jcdb.impl.storage.jooq.tables.Symbols


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SymbolsRecord() : UpdatableRecordImpl<SymbolsRecord>(Symbols.SYMBOLS), Record3<Long?, String?, Long?> {

    var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    var hash: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<Long?, String?, Long?> = super.fieldsRow() as Row3<Long?, String?, Long?>
    override fun valuesRow(): Row3<Long?, String?, Long?> = super.valuesRow() as Row3<Long?, String?, Long?>
    override fun field1(): Field<Long?> = Symbols.SYMBOLS.ID
    override fun field2(): Field<String?> = Symbols.SYMBOLS.NAME
    override fun field3(): Field<Long?> = Symbols.SYMBOLS.HASH
    override fun component1(): Long? = id
    override fun component2(): String? = name
    override fun component3(): Long? = hash
    override fun value1(): Long? = id
    override fun value2(): String? = name
    override fun value3(): Long? = hash

    override fun value1(value: Long?): SymbolsRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): SymbolsRecord {
        this.name = value
        return this
    }

    override fun value3(value: Long?): SymbolsRecord {
        this.hash = value
        return this
    }

    override fun values(value1: Long?, value2: String?, value3: Long?): SymbolsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised SymbolsRecord
     */
    constructor(id: Long? = null, name: String? = null, hash: Long? = null): this() {
        this.id = id
        this.name = name
        this.hash = hash
    }
}
