/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables


import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.utbot.jcdb.impl.storage.jooq.DefaultSchema
import org.utbot.jcdb.impl.storage.jooq.keys.ANNOTATIONS__
import org.utbot.jcdb.impl.storage.jooq.tables.records.AnnotationsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Annotations(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, AnnotationsRecord>?,
    aliased: Table<AnnotationsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<AnnotationsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>Annotations</code>
         */
        val ANNOTATIONS: Annotations = Annotations()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AnnotationsRecord> = AnnotationsRecord::class.java

    /**
     * The column <code>Annotations.id</code>.
     */
    val ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.annotation_name</code>.
     */
    val ANNOTATION_NAME: TableField<AnnotationsRecord, Long?> = createField(DSL.name("annotation_name"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>Annotations.visible</code>.
     */
    val VISIBLE: TableField<AnnotationsRecord, Boolean?> = createField(DSL.name("visible"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>Annotations.parent_annotation</code>.
     */
    val PARENT_ANNOTATION: TableField<AnnotationsRecord, Long?> = createField(DSL.name("parent_annotation"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.class_id</code>.
     */
    val CLASS_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("class_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.method_id</code>.
     */
    val METHOD_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("method_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.field_id</code>.
     */
    val FIELD_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("field_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Annotations.param_id</code>.
     */
    val PARAM_ID: TableField<AnnotationsRecord, Long?> = createField(DSL.name("param_id"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<AnnotationsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<AnnotationsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>Annotations</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>Annotations</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>Annotations</code> table reference
     */
    constructor(): this(DSL.name("Annotations"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, AnnotationsRecord>): this(Internal.createPathAlias(child, key), child, key, ANNOTATIONS, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<AnnotationsRecord> = ANNOTATIONS__
    override fun `as`(alias: String): Annotations = Annotations(DSL.name(alias), this)
    override fun `as`(alias: Name): Annotations = Annotations(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Annotations = Annotations(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Annotations = Annotations(name, null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Long?, Long?, Boolean?, Long?, Long?, Long?, Long?, Long?> = super.fieldsRow() as Row8<Long?, Long?, Boolean?, Long?, Long?, Long?, Long?, Long?>
}
