/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables


import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.utbot.jcdb.impl.storage.jooq.DefaultSchema
import org.utbot.jcdb.impl.storage.jooq.keys.CLASSHIERARCHIES__
import org.utbot.jcdb.impl.storage.jooq.tables.records.ClasshierarchiesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Classhierarchies(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, ClasshierarchiesRecord>?,
    aliased: Table<ClasshierarchiesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<ClasshierarchiesRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>ClassHierarchies</code>
         */
        val CLASSHIERARCHIES: Classhierarchies = Classhierarchies()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ClasshierarchiesRecord> = ClasshierarchiesRecord::class.java

    /**
     * The column <code>ClassHierarchies.id</code>.
     */
    val ID: TableField<ClasshierarchiesRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>ClassHierarchies.class_id</code>.
     */
    val CLASS_ID: TableField<ClasshierarchiesRecord, Long?> = createField(DSL.name("class_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>ClassHierarchies.super_id</code>.
     */
    val SUPER_ID: TableField<ClasshierarchiesRecord, Long?> = createField(DSL.name("super_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>ClassHierarchies.is_class_ref</code>.
     */
    val IS_CLASS_REF: TableField<ClasshierarchiesRecord, Boolean?> = createField(DSL.name("is_class_ref"), SQLDataType.BOOLEAN.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ClasshierarchiesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<ClasshierarchiesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>ClassHierarchies</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>ClassHierarchies</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>ClassHierarchies</code> table reference
     */
    constructor(): this(DSL.name("ClassHierarchies"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, ClasshierarchiesRecord>): this(Internal.createPathAlias(child, key), child, key, CLASSHIERARCHIES, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getPrimaryKey(): UniqueKey<ClasshierarchiesRecord> = CLASSHIERARCHIES__
    override fun `as`(alias: String): Classhierarchies = Classhierarchies(DSL.name(alias), this)
    override fun `as`(alias: Name): Classhierarchies = Classhierarchies(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Classhierarchies = Classhierarchies(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Classhierarchies = Classhierarchies(name, null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Long?, Long?, Long?, Boolean?> = super.fieldsRow() as Row4<Long?, Long?, Long?, Boolean?>
}
