/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.tables


import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.Name
import org.jooq.Record
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.utbot.jcdb.impl.storage.jooq.DefaultSchema
import org.utbot.jcdb.impl.storage.jooq.indexes.FIELDS_CLASS_ID_NAME
import org.utbot.jcdb.impl.storage.jooq.keys.FIELDS__
import org.utbot.jcdb.impl.storage.jooq.tables.records.FieldsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Fields(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, FieldsRecord>?,
    aliased: Table<FieldsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<FieldsRecord>(
    alias,
    DefaultSchema.DEFAULT_SCHEMA,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>Fields</code>
         */
        val FIELDS: Fields = Fields()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FieldsRecord> = FieldsRecord::class.java

    /**
     * The column <code>Fields.id</code>.
     */
    val ID: TableField<FieldsRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>Fields.access</code>.
     */
    val ACCESS: TableField<FieldsRecord, Int?> = createField(DSL.name("access"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>Fields.name</code>.
     */
    val NAME: TableField<FieldsRecord, Long?> = createField(DSL.name("name"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>Fields.signature</code>.
     */
    val SIGNATURE: TableField<FieldsRecord, String?> = createField(DSL.name("signature"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>Fields.field_class</code>.
     */
    val FIELD_CLASS: TableField<FieldsRecord, Long?> = createField(DSL.name("field_class"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>Fields.class_id</code>.
     */
    val CLASS_ID: TableField<FieldsRecord, Long?> = createField(DSL.name("class_id"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<FieldsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<FieldsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>Fields</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>Fields</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>Fields</code> table reference
     */
    constructor(): this(DSL.name("Fields"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, FieldsRecord>): this(Internal.createPathAlias(child, key), child, key, FIELDS, null)
    override fun getSchema(): Schema? = if (aliased()) null else DefaultSchema.DEFAULT_SCHEMA
    override fun getIndexes(): List<Index> = listOf(FIELDS_CLASS_ID_NAME)
    override fun getPrimaryKey(): UniqueKey<FieldsRecord> = FIELDS__
    override fun `as`(alias: String): Fields = Fields(DSL.name(alias), this)
    override fun `as`(alias: Name): Fields = Fields(alias, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Fields = Fields(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Fields = Fields(name, null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Long?, Int?, Long?, String?, Long?, Long?> = super.fieldsRow() as Row6<Long?, Int?, Long?, String?, Long?, Long?>
}
