/*
 * This file is generated by jOOQ.
 */
package org.utbot.jcdb.impl.storage.jooq.indexes


import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.utbot.jcdb.impl.storage.jooq.tables.Calls
import org.utbot.jcdb.impl.storage.jooq.tables.Fields
import org.utbot.jcdb.impl.storage.jooq.tables.Methods
import org.utbot.jcdb.impl.storage.jooq.tables.Symbols



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val `CALLS FIELDS`: Index = Internal.createIndex(DSL.name("Calls fields"), Calls.CALLS, arrayOf(Calls.CALLS.CALLEE_CLASS_HASH, Calls.CALLS.CALLEE_FIELD_HASH, Calls.CALLS.LOCATION_ID), false)
val `CALLS METHODS`: Index = Internal.createIndex(DSL.name("Calls methods"), Calls.CALLS, arrayOf(Calls.CALLS.CALLEE_CLASS_HASH, Calls.CALLS.CALLEE_METHOD_HASH, Calls.CALLS.LOCATION_ID), false)
val FIELDS_CLASS_ID_NAME: Index = Internal.createIndex(DSL.name("Fields_class_id_name"), Fields.FIELDS, arrayOf(Fields.FIELDS.CLASS_ID, Fields.FIELDS.NAME), true)
val METHODS_CLASS_ID_NAME_DESC: Index = Internal.createIndex(DSL.name("Methods_class_id_name_desc"), Methods.METHODS, arrayOf(Methods.METHODS.CLASS_ID, Methods.METHODS.NAME, Methods.METHODS.DESC), true)
val SYMBOLS_NAME: Index = Internal.createIndex(DSL.name("Symbols_name"), Symbols.SYMBOLS, arrayOf(Symbols.SYMBOLS.NAME), true)
