name: Nightly builds for Maven Central

on:
  schedule:
    - cron: '30 23 * * 1,2,3,4,5'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          gradle-version: 7.4.2
          arguments: | 
            publish
            -Pactor=${{ secrets.MAVEN_CENTRAL_LOGIN }}
            -Ptoken=${{ secrets.MAVEN_CENTRAL_TOKEN }}
            -PrepoUrl=https://s01.oss.sonatype.org/content/repositories/snapshots/
